### ISSUE TITLE
Mangler stedsnavn?

### ISSUE THREAD

**Issue by NKAmapper** [obtitus/ssr2_to_osm#1]
Etter siste kjøring fikk mange kommuner flere stedsnavn, men disse kommunene fikk en kraftig nedgang: Ringerike, Drangedal, Tinn, Grimstad, Lindesnes, Sunnfjord, Trondheim, Nærøysund, Senja, Kautokeino.

Dersom WFS'en er ustabil kan kanskje denne alternative kilden brukes, der komplette filer kan leses direkte: https://nedlasting.geonorge.no/geonorge/Basisdata/Stedsnavn/GML/ (litt forskjellig namespace/struktur ift. WFS).

**Comment by obtitus** [comment]
Ja, ser det er tilfeldig om jeg får lastet ned hele datasettet, la inn en retry on failure, ser ikke ut som det løste saken. Prøvde å bytte fra requests til urllib, ser ikke ut som det hjalp. Litt håpløst når jeg får status OK fra serveren, det bare mangler en masse noder.

Har begynt å se på linken du sendte.

**Comment by NKAmapper** [comment]
I kjøringen 28/12 ser det ut til at de nevnte kommunene har fått flere stedsnavn igjen. Men nå har 13 kommuner ingen stedsnavn i det hele tatt (null): Kongsvinger, Øygarden, Karsløy osv.

**Comment by obtitus** [comment]
Ja, vet, jeg trodde jeg kom meg ganske langt med gml filene, men når jeg differ resultatet så er det veldig mange forskjeller, så da stoppet det litt opp. Virker som om det er mere enn bare strukturen som er litt forskjellig...

**Comment by NKAmapper** [comment]
Jeg kan hjelpe med å se på forskjellene om du har en av de gamle filene.

**Comment by NKAmapper** [comment]
Jeg har vært i kontakt med Kartverket. De kjenner til et problem der kommunikasjonen avbrytes før overføringen av data er ferdig, slik at </wfs:FeatureCollection> mangler. De skulle sjekke om noe kan gjøres. I mellomtiden er løsningen å lese flere ganger helt til </wfs:FeatureCollection> er med. Jeg testet 10 innlesinger av samme kall og fikk fullstendige data 1 gang, men det kan ha vært tilfeldig, så jeg vet ikke egentlig hvor mange forsøk man må regne med når nedlastingen først feiler.

I mellomtiden har jeg laget et lite skript her som leser fra de ferdige filene hos GeoNorge: https://github.com/NKAmapper/ssr2osm. Det ser ut til å gi riktige filer (en forskjell er at _undernavn_ ikke løftes til name=*).

**Comment by NKAmapper** [comment]
Kartverket melder tilbake i dag at de har endret en konfigurering på serversiden, og nå får jeg komplette resultater i alle tester.

**Comment by obtitus** [comment]
Hei, beklager treig respons, kjørte ny xml kjøring nå, ser jo lovende ut.
